### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by harikt** [Hywan/Marvirc#4]
Hi @Hywan , 

This is regarding to a question asked over https://github.com/hoaproject/Marvirc/issues/4 .

What I think of a bot is something that logs the messages on the channel. I don't see anything logged / shown or can send some message to the channel . I may be wrong with what I expect. May be you could tell what the purpose of the ircbot really is ?

**Comment by Hywan** [comment]
@harikt Marvirc does not save logs automatically. You have to create a special command for that. We can land a default command to address this need thought but several questions happen then (please, see https://github.com/hoaproject/ActionBoard/issues/2).

Did I understand correctly? You want a bot that logs stuff for you, correct?

**Comment by harikt** [comment]
@Hywan you are correct. I see now Marvirc is not what I was looking for, but it can be made possible.

**Comment by Hywan** [comment]
I understand the question has been answered. Feel free to re-open if I misunderstood!

**Comment by harikt** [comment]
sure.

Thanks!

*Hari K T*

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt
